### ISSUE TITLE
Documentation & pre-trained models

### ISSUE THREAD

**Issue by JohannesTK** [cutz-j/FakeTalkerDetect#1]
Hi,

Do you have a more detailed readme and pre-trained models? Would love to make use of your research.

Thank you.

**Comment by cutz-j** [comment]
Sorry for a late answer.
We are improving our work (version 2 or similar subject but other method) and preparing some paper works.
Before ICCV HBU Workshop (submitted), we plan to commit README and run file (dataset).
Please wait for things. Thanks!
