### ISSUE TITLE
object of type 'generator' has no len()

### ISSUE THREAD

**Issue by zia7** [cutz-j/FakeTalkerDetect#2]
can you please check if this error is related to your dataset or issue in my colab settings

 for i in trange(len(test_generator)):
TypeError: object of type 'generator' has no len()

![git](https://user-images.githubusercontent.com/65252065/82117391-0e08e880-9789-11ea-930c-9e47172bddca.png)

**Comment by cutz-j** [comment]
Sorry for a late answer.
Could you check that data directory is right?
